image: gitpod/workspace-full

tasks:
  - name: Install AWS CLI
    before: |
      (
        curl -fSsl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -qq awscliv2.zip
        sudo ./aws/install --update
        rm awscliv2.zip
      )

  - name: Install SAM CLI
    before: brew install aws/tap/aws-sam-cli

  - name: Start DynamoDB
    before: docker-compose pull
    init: docker-compose up

#   - name: Init DynamoDb
#     command: sh ./dynamodb-init.sh

#   - name: Start Lambda functions
#     init: sam build
#     command: sam local rocketnotes-serverless-api --docker-network rocketnotes_local-serverless-network --warm-containers EAGER 

#   - name: Start webapp
#     before: export BASE_API_URL="http://localhost:3000"
#     init: |
#       (
#         cd webapp
#         npm install
#       )
#     command: npm run start

# ports:
#   - port: 8000
#     onOpen: ignore
#   - port: 3000
#     onOpen: open-preview
#     name: Website
#     description: Website Preview