image: gitpod/workspace-full

tasks:
  - name: Start DynamoDB
    before: docker-compose pull
    init: docker-compose up

  - name: Init DynamoDb
    before: |
      (
        curl -fSsl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -qq awscliv2.zip
        sudo ./aws/install --update
        rm awscliv2.zip
        aws configure set aws_access_key_id 123
        aws configure set aws_access_key_id 123
        aws configure set region us-east-1
      )
    command: bash $GITPOD_REPO_ROOT/dynamodb-init.sh

  - name: Start Lambda functions
    before: brew install aws/tap/aws-sam-cli
    init: sam build
    command: sam local start-api --docker-network rocketnotes_local-serverless-network --warm-containers EAGER 

  - name: Start webapp
    init: |
      (
        cd webapp
        npm install
      )
    command: |
      (
        cd webapp
        npm run start-gitpod
      )

ports:
  - port: 4200
    onOpen: open-preview
    name: Website
    description: Website Preview
  - port: 3000
    onOpen: ignore
    name: Api
  - port: 8041
    onOpen: ignore
    name: Db