# This image is used to run lambda functions locally
FROM public.ecr.aws/sam/build-go1.x:latest

RUN mkdir /app

WORKDIR /app

COPY template.yaml .
COPY lambda-handler ./lambda-handler
COPY go.mod .
COPY go.sum .