FROM public.ecr.aws/sam/build-provided.al2:latest

WORKDIR /var/task

COPY template.yaml .
COPY go.mod .
COPY go.sum .
COPY handler-go ./handler-go
COPY handler-py ./handler-py
COPY .aws-sam ./.aws-sam

EXPOSE 3002
