AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: "'GET,POST,DELETE,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  getDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/get-document-handler
      Handler: get-document-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /document/{documentId}
            Method: GET

  getDocumentTreeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/get-document-tree-handler
      Handler: get-document-tree-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-tree
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /documentTree/{userId}
            Method: GET

  saveDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/save-document-handler
      Handler: local.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
        - DynamoDBCrudPolicy:
            TableName: tnn-tree
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /saveDocument
            Method: POST

  saveDocumentTreeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/save-document-tree-handler
      Handler: save-document-tree-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-tree
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /saveDocumentTree
            Method: POST

  saveDocumentPublicFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/save-document-public-handler
      Handler: save-document-public-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /shareDocument
            Method: POST

  saveDocumentTitleFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/save-document-title-handler
      Handler: save-document-title-handler
      Runtime: go1.x
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /saveDocumentTitle
            Method: POST

  searchDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/search-document-handler
      Handler: search-document-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /search-documents/{userId}
            Method: GET

  getSharedDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/get-shared-document-handler
      Handler: get-shared-document-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /shared/{documentId}
            Method: GET

  deleteDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/delete-document-handler
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-Documents
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /deleteDocument/{id}
            Method: DELETE

  saveVectorEmbeddingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 8192
      Timeout: 900
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
        - DynamoDBCrudPolicy:
            TableName: tnn-vectors
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          LOCAL: 1
          BUCKET_NAME: faissIndexBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /vector-embeddings
            Method: POST
    Metadata:
      DockerContext: handler-ai/rocketnotes_handler
      Dockerfile: handler_vector_embeddings/Dockerfile.local

  semanticSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          LOCAL: 1
          BUCKET_NAME: faissIndexBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /semanticSearch
            Method: POST
    Metadata:
      DockerContext: handler-ai/rocketnotes_handler
      Dockerfile: handler_semantic_search/Dockerfile.local

  chatFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          LOCAL: 1
          BUCKET_NAME: faissIndexBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /chat
            Method: POST
    Metadata:
      DockerContext: handler-ai/rocketnotes_handler
      Dockerfile: handler_chat/Dockerfile.local

  saveUserConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/save-user-config-handler
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /userConfig
            Method: POST

  getUserConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/get-user-config-handler
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /userConfig/{userId}
            Method: GET 

  getZettelkastenFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/get-zettelkasten-handler
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-Zettelkasten
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /zettelkasten/{userId}
            Method: GET 

  saveZettelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/save-zettel-handler
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-Zettelkasten
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /saveZettel
            Method: POST

  deleteZettelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/delete-zettel-handler
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-Zettelkasten
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /deleteZettel/{id}
            Method: DELETE

  archiveZettelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handler-crud/archive-zettel-handler
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /archiveZettel/{documentId}
            Method: POST

  vibeGenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          LOCAL: 1
          BUCKET_NAME: faissIndexBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /vibe/generate/{userId}
            Method: GET
    Metadata:
      DockerContext: handler-ai/rocketnotes_handler
      Dockerfile: handler_vibe/Dockerfile

  vibeInsightsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          LOCAL: 1
          BUCKET_NAME: faissIndexBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /vibe/insert/{userId}
            Method: POST
    Metadata:
      DockerContext: handler-ai/rocketnotes_handler
      Dockerfile: handler_insert/Dockerfile
