AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  helloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/hello-world-handler
      Handler: local.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello-world
            Method: GET

  getDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/get-document-handler
      Handler: get-document-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /document/{documentId}
            Method: GET

  getDocumentTreeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/get-document-tree-handler
      Handler: get-document-tree-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-tree
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /documentTree/{userId}
            Method: GET

  saveDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/save-document-handler
      Handler: local.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /saveDocument
            Method: POST

  saveDocumentTreeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/save-document-tree-handler
      Handler: save-document-tree-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-tree
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /saveDocumentTree
            Method: POST

  saveDocumentPublicFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/save-document-public-handler
      Handler: save-document-public-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /shareDocument
            Method: POST

  saveDocumentTitleFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/save-document-title-handler
      Handler: save-document-title-handler
      Runtime: go1.x
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /saveDocumentTitle
            Method: POST

  searchDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/search-document-handler
      Handler: search-document-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /search-documents/{userId}
            Method: GET

  getSharedDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/get-shared-document-handler
      Handler: get-shared-document-handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /shared/{documentId}
            Method: GET

  saveVectorEmbeddingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 4096
      Timeout: 900
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
        - DynamoDBCrudPolicy:
            TableName: tnn-vectors
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          LOCAL: 1
          BUCKET_NAME: faissIndexBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /vector-embeddings
            Method: POST
    Metadata:
      DockerContext: lambda-handler/save-vector-embeddings-handler
      Dockerfile: Dockerfile

  semanticSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          LOCAL: 1
          BUCKET_NAME: faissIndexBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /semanticSearch
            Method: POST
    Metadata:
      DockerContext: lambda-handler/semantic-search-handler
      Dockerfile: Dockerfile

  chatFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-documents
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          LOCAL: 1
          BUCKET_NAME: faissIndexBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /chat
            Method: POST
    Metadata:
      DockerContext: lambda-handler/chat-handler
      Dockerfile: Dockerfile

  saveUserConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/save-user-config-handler
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /userConfig
            Method: POST

  getUserConfigFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda-handler/get-user-config-handler
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tnn-userConfig
      Environment:
        Variables:
          USE_LOCAL_DYNAMODB: 1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /userConfig/{userId}
            Method: GET 

  textCompletionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-handler/text-completion-handler
      Handler: main.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /text-completion
            Method: POST

